CREATE TABLE media (

    id INT AUTO_INCREMENT PRIMARY KEY,

    file_name VARCHAR(255) NOT NULL,

    file_path VARCHAR(500) NOT NULL,

    type VARCHAR(50) DEFAULT 'image',

    size INT DEFAULT 0,

    uploaded_by INT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,


    FOREIGN KEY (uploaded_by)
    REFERENCES users(id)
    ON DELETE SET NULL

);
