CREATE TABLE seo_settings (

    id INT AUTO_INCREMENT PRIMARY KEY,

    page VARCHAR(100) NOT NULL UNIQUE,

    title VARCHAR(255) NOT NULL,

    description TEXT,

    keywords VARCHAR(500),

    image VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP

);
